DATA:
  data_root: dataset/IQON3000
  train_data_ori: dataset/IQON3000/data/train.csv
  valid_data_ori: dataset/IQON3000/data/valid.csv
  test_data_ori: dataset/IQON3000/data/test.csv
  visual_features_dict_ori: dataset/IQON3000/feat/visualfeatures
  textural_idx_dict_ori: dataset/IQON3000/feat/textfeatures
  textural_embedding_matrix: dataset/IQON3000/feat/smallnwjc2vec
  user_map: dataset/IQON3000/data/user_map.json
  item_map: dataset/IQON3000/data/item_map.json
  visual_features_tensor: dataset/IQON3000/feat/visualfeatures_indexedtenseor
  textural_features_tensor: dataset/IQON3000/feat/textfeatures_indexedtenseor
  train_data: dataset/IQON3000/data/train_indexed.csv
  valid_data: dataset/IQON3000/data/valid_indexed.csv
  test_data: dataset/IQON3000/data/test_indexed.csv

TRAIN:
  arch: VBPR
  dataset: IQON3000
  epochs: 80
  start_epoch: 0
  max_sentence: 83
  print_freq: 1
  workers: 2
  batch_size: 1024
  hidden_dim: 512
  text_feature_dim: 300
  visual_feature_dim: 2048
  gpu: [0]
  base_lr: 0.001 # learning rate
  wd: 0.00001 # weight decay 
  patience: 5 # for early stop
  with_Nor: True # Feature Scaling
  weight:  # path to initial weight (default: none)
  resume:  # 
  save_path: saved/IQON3000/VBPR
  evaluate: True
  batch_size_val: 1024
  save_freq: 1

TEST:
  test_batch_size: 1024
  model_path:      # evaluation model path
  save_folder:    #test results save folder
